// <auto-generated />
namespace VegetableWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RolesIdNewProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RolesIdNewProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201710011312174_RolesIdNewProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
